
build:
  image: teaci/msys$$arch
  shell: mingw$$arch
  pull: true
  commands:
    - if [ $$arch = 32 ]; then target=i686; fi
    - if [ $$arch = 64 ]; then target=x86_64; fi
    - pacman -S --noconfirm mingw-w64-${target}-libuv mingw-w64-${target}-luajit-git mingw-w64-${target}-lua51-lpeg mingw-w64-${target}-msgpack-c mingw-w64-${target}-cmake
    - mkdir build
    - cd build
    - cmake .. -G "MSYS Makefiles"
    - make

matrix:
  arch:
    - 32
    - 64
