
build:
  image: teaci/msys$$arch
  shell: mingw$$arch
  pull: true
  commands:
    - if [ $$arch = 32 ]; then target=i686; fi
    - if [ $$arch = 64 ]; then target=x86_64; fi
    - pacman -S --noconfirm winpty mingw-w64-${target}-cmake mingw-w64-${target}-make mingw-w64-${target}-perl mingw-w64-${target}-python2
    - cmd /c "call .ci/teaci_build_deps.bat"
    - cmd /c "call .ci/teaci_build.bat"

matrix:
  arch:
    - 32
    - 64
