version: '{build}'
skip_tags: true
environment:
  # The default cpack in the PATH is not CMake
  CPACK: C:\Program Files (x86)\CMake\bin\cpack.exe
  matrix:
  - BUILD_DEPS_SCRIPT: .ci\vs2015_build_deps.bat
    BUILD_SCRIPT: .ci\vs2015_build.bat
  - BUILD_DEPS_SCRIPT: .ci\mingw_build_deps.bat
    BUILD_SCRIPT: .ci\mingw_build.bat
install: []
build_script:
- cmd: '%BUILD_DEPS_SCRIPT%'
- cmd: '%BUILD_SCRIPT%'
# Build artifacts
- cd build
- '"%CPACK%" -G NSIS -C Release'
- '"%CPACK%" -G ZIP -C Release'
artifacts:
- path: build/Neovim.zip
- path: build/Neovim.exe
