version: '{build}'
skip_tags: true
environment:
  GYP_MSVS_VERSION: 2015
  matrix:
  - GENERATOR: Visual Studio 14 Win64
    DEPS_PATH: deps64
  - GENERATOR: Visual Studio 14
    DEPS_PATH: deps32
    BUILD_NUPKG: 1
# Currently not working in appveyor, maybe its the compiler version
#  - GENERATOR: MinGW Makefiles
#    DEPS_PATH: deps-mingw
install: []
build_script:
# See http://help.appveyor.com/discussions/problems/539-cloning-gyp-fails
- git config --global url."http://".insteadOf https://
# Workaround for CMake not wanting sh.exe on PATH for MinGW
- set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
# Mingw MUST be first in path otherwise CMake will block
# see http://help.appveyor.com/discussions/problems/2371-mingw-build-started-hanging-without-output
- if "%GENERATOR%" == "MinGW Makefiles" set PATH=C:\MinGW\bin;%PATH%
- mkdir %DEPS_PATH%
- cd %DEPS_PATH%
- cmake -G "%GENERATOR%" ..\third-party\
- cmake --build .
- cd ..
- mkdir build
- cd build
- cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=Debug -DDEPS_PREFIX=..\%DEPS_PATH%\usr -DCMAKE_INSTALL_PREFIX=..\INSTALL ..
- cmake --build .
- bin\nvim.exe --version
- cmake --build . --target install
- if DEFINED BUILD_NUPKG nuget pack -Version 0.0.0-pr810 ..\contrib\neovim.nuspec
nuget:
  project_feed: true
artifacts:
- path: INSTALL
  name: Neovim
- path: 'build/*.nupkg'
  name: nupkgs
