version: '{build}'
skip_tags: true
environment:
  matrix:
  - BUILD_DEPS_SCRIPT: .ci\vs2015_build_deps.bat
  - BUILD_DEPS_SCRIPT: .ci\mingw_build_deps.bat
install: []
build_script:
- cmd: '%BUILD_DEPS_SCRIPT%'
